### ISSUE TITLE
Migrate Infrastructure

### ISSUE THREAD

**Issue by timonmasberg** [kordis-leitstelle/kordis#306]
Due to Microsoft reducing the annual grant in the Azure Sponsorship program, we cannot fully host our application stack on Azure anymore. We need to immediately migrate to a self-hosted solution...

- [x] evaluate which solution we want to use for our cluster (microk8s, k3s, k0s are popular solutions)
- [x] setup k8s on the server 
- [x] setup infra repo @JSPRH 
- [x]  Build, tag and publish image in pipeline @JSPRH 
- [ ] migrate CI/CD towards server new infra (next and prod deployment, next E2Es) @timonmasberg 
- [ ] ensure that our infrastructure is easily maintainable and described in a way that we can easily spin it up somewhere else (https://github.com/kordis-leitstelle/kordis/issues/138, thus we probably need to set up https://github.com/kordis-leitstelle/kordis/issues/176 for our k8s configs) @JSPRH 
- [ ] setup next and prod environments, ensure option for dynamic environment creation (preview environments)
- [ ] update documentation, especially the landscape, write ADR on why we had to move to a bare-metal solution
- [ ] spin down every azure resource we are not going to need anymore
- [ ] Backup strategy (kubernetes volumes snapshot)
- [ ] [harden server](https://github.com/seatonjiang/aegis)

**Comment by JSPRH** [comment]
Our new infrastructure repo (private) is here! https://github.com/kordis-leitstelle/infrastructure
